name: CI

on:
  push:
  pull_request:
    branches:
      - '*'
  
  label:
    types: [created, edited]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        SERVICE_ID: ${{ secrets.SERVICE_ID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}

    - name: Deploy
      uses: ZackKuptsow/github-pages-deploy
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
